// Diagram model → SVG, drawn with D3 into a jsdom document. See spec §5.
import * as d3 from 'd3';
import { JSDOM } from 'jsdom';

const FONT = 'Arial, Helvetica, sans-serif';
const C = { box: '#404040', ink: '#000000', paper: '#ffffff', muted: '#666666' };

// Helvetica advance widths (1/1000 em) for ASCII 32..126 — no text metrics in Node.
const W = [278,278,355,556,556,889,667,191,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,278,278,584,584,584,556,1015,667,667,722,722,667,611,778,722,278,500,667,556,833,722,778,667,778,722,667,611,722,667,944,667,667,611,278,278,278,469,556,333,556,556,500,556,556,278,556,556,222,222,500,222,833,556,556,556,556,333,500,278,556,500,722,500,500,500,334,260,334,584];
export function textWidth(s, size = 12, bold = false) {
  let w = 0;
  for (const ch of String(s)) { const c = ch.charCodeAt(0); w += (c >= 32 && c <= 126 ? W[c - 32] : 600); }
  return (w / 1000) * size * (bold ? 1.07 : 1);
}

// Greedy word wrap to at most `maxLines` lines within `maxW` px.
function wrap(s, maxW, size, maxLines = 2) {
  const words = String(s).split(' ');
  const lines = [];
  let cur = '';
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (textWidth(next, size) <= maxW || !cur) cur = next;
    else { lines.push(cur); cur = w; }
  }
  if (cur) lines.push(cur);
  if (lines.length > maxLines) {
    const head = lines.slice(0, maxLines - 1);
    head.push(lines.slice(maxLines - 1).join(' '));
    return head;
  }
  return lines;
}

const L = {
  margin: 30, titleH: 50, fs: 12,
  boxPad: 30, rectH: 30, rectGap: 10, rectMinW: 560,
  sidCols: 3, sidH: 38, sidGap: 16, sidTop: 40,
  apiPitch: 46, stub: 150, r: 10, labelGap: 24,
  noteH: 30, legendH: 64, legendGap: 30,
};

export function renderSvg(model) {
  const { document, XMLSerializer } = new JSDOM('<!DOCTYPE html><body></body>').window;

  // ---- measure --------------------------------------------------------------
  const fs = L.fs;
  const labelW = (apis) => Math.max(0, ...apis.map((a) => textWidth(a.label, fs, a.required)));
  const leftLabelW = labelW(model.dependent), rightLabelW = labelW(model.exposed);
  const leftGutter = Math.max(L.stub, leftLabelW + L.labelGap) + L.r * 2;
  const rightGutter = Math.max(L.stub, rightLabelW + L.labelGap) + L.r * 2;

  const etoms = model.etoms.length ? model.etoms
    : [{ label: 'No eTOM business activities assigned', tooltip: 'componentMetadata.eTOMs is empty', placeholder: true }];
  const rectW = Math.max(L.rectMinW, ...etoms.map((e) => textWidth(e.label, fs) + 16));
  const boxW = rectW + L.boxPad * 2;
  const etomH = etoms.length * (L.rectH + L.rectGap) - L.rectGap;
  const sidRows = Math.ceil(model.sids.length / L.sidCols);
  const sidH = sidRows ? L.sidTop + sidRows * (L.sidH + L.sidGap) - L.sidGap : 0;
  const contentH = L.boxPad * 2 + etomH + sidH;
  const apiH = L.boxPad * 2 + Math.max(model.dependent.length, model.exposed.length) * L.apiPitch;
  const boxH = Math.max(contentH, apiH, 200);

  const boxX = Math.round(L.margin + leftGutter), boxY = L.margin + L.titleH;
  const pageW = boxX + boxW + rightGutter + L.margin;
  const legendY = boxY + boxH + L.noteH + L.legendGap;
  const pageH = legendY + L.legendH + L.margin;

  // ---- draw -----------------------------------------------------------------
  const svg = d3.select(document.body).append('svg')
    .attr('xmlns', 'http://www.w3.org/2000/svg')
    .attr('version', '1.1')
    .attr('width', Math.ceil(pageW)).attr('height', Math.ceil(pageH))
    .attr('viewBox', `0 0 ${Math.ceil(pageW)} ${Math.ceil(pageH)}`)
    .attr('font-family', FONT).attr('font-size', fs);
  svg.append('title').text(model.title);
  svg.append('desc').text(
    `ODA component architecture for ${model.id} (component.yaml v${model.version}, ${model.status}). ` +
    `Exposed APIs on the right, dependent APIs on the left. Generated by skills/svg-diagram.`);
  svg.append('rect').attr('width', '100%').attr('height', '100%').attr('fill', C.paper);

  svg.append('text').attr('x', L.margin).attr('y', L.margin + 10)
    .attr('font-size', 16).attr('font-weight', 'bold').attr('fill', C.ink).text(model.title);

  // component box
  const box = svg.append('g').attr('id', 'component').attr('transform', `translate(${boxX},${boxY})`);
  box.append('rect').attr('width', boxW).attr('height', boxH).attr('fill', C.box).attr('stroke', C.ink);

  // eTOM activities
  const et = box.append('g').attr('id', 'etoms').selectAll('g').data(etoms).join('g')
    .attr('class', 'etom')
    .attr('transform', (_, i) => `translate(${L.boxPad},${L.boxPad + i * (L.rectH + L.rectGap)})`);
  et.append('title').text((d) => d.tooltip);
  et.append('rect').attr('width', rectW).attr('height', L.rectH).attr('fill', C.paper).attr('stroke', C.ink);
  et.append('text').attr('x', 6).attr('y', L.rectH / 2).attr('dy', '0.35em')
    .attr('fill', (d) => (d.placeholder ? C.muted : C.ink))
    .attr('font-style', (d) => (d.placeholder ? 'italic' : null))
    .text((d) => d.label);

  // SID entities as cylinders
  const colW = (rectW - (L.sidCols - 1) * L.sidGap) / L.sidCols;
  const cylW = Math.min(colW, 200), ry = 5;
  const sidY0 = L.boxPad + etomH + L.sidTop;
  const sid = box.append('g').attr('id', 'sids').selectAll('g').data(model.sids).join('g')
    .attr('class', 'sid')
    .attr('transform', (_, i) => {
      const col = i % L.sidCols, row = Math.floor(i / L.sidCols);
      const x = L.boxPad + col * (colW + L.sidGap) + (colW - cylW) / 2;
      return `translate(${x},${sidY0 + row * (L.sidH + L.sidGap)})`;
    });
  sid.append('title').text((d) => d.tooltip);
  sid.append('path').attr('fill', C.paper).attr('stroke', C.ink)
    .attr('d', `M0,${ry} A${cylW / 2},${ry} 0 0 1 ${cylW},${ry} V${L.sidH - ry} A${cylW / 2},${ry} 0 0 1 0,${L.sidH - ry} Z`);
  sid.append('path').attr('fill', 'none').attr('stroke', C.ink)
    .attr('d', `M0,${ry} A${cylW / 2},${ry} 0 0 0 ${cylW},${ry}`);
  sid.each(function (d) {
    const lines = wrap(d.label, cylW - 10, fs);
    const t = d3.select(this).append('text').attr('text-anchor', 'middle').attr('fill', C.ink);
    const cy = ry + (L.sidH - ry) / 2 - ((lines.length - 1) * 13) / 2;
    lines.forEach((ln, i) => t.append('tspan').attr('x', cylW / 2).attr('y', cy + i * 13).attr('dy', '0.35em').text(ln));
  });

  // API connector rows, evenly spread down the box on each side
  const rowY = (i, n) => {
    const pitch = Math.min(L.apiPitch * 1.3, (boxH - L.boxPad * 2) / Math.max(n, 1));
    return L.boxPad + (i + 0.5) * pitch;
  };

  // dependent (left): socket = half circle opening to the left, line into the box
  const dep = svg.append('g').attr('id', 'dependent-apis').selectAll('g').data(model.dependent).join('g')
    .attr('class', 'dependent-api').attr('data-api', (d) => d.id)
    .attr('transform', (_, i, a) => `translate(${L.margin},${boxY + rowY(i, a.length)})`);
  dep.append('title').text((d) => d.tooltip);
  dep.append('path').attr('fill', 'none').attr('stroke', C.ink).attr('stroke-width', 2)
    .attr('d', `M${L.r},${-L.r} A${L.r},${L.r} 0 0 1 ${L.r},${L.r}`);
  dep.append('line').attr('x1', L.r * 2).attr('x2', leftGutter).attr('y1', 0).attr('y2', 0)
    .attr('stroke', C.ink).attr('stroke-width', 2);
  dep.append('text').attr('x', L.r + leftGutter / 2).attr('y', -7).attr('text-anchor', 'middle')
    .attr('fill', C.ink).attr('font-weight', (d) => (d.required ? 'bold' : null)).text((d) => d.label);

  // exposed (right): lollipop = line out of the box ending in a circle
  const exp = svg.append('g').attr('id', 'exposed-apis').selectAll('g').data(model.exposed).join('g')
    .attr('class', 'exposed-api').attr('data-api', (d) => d.id)
    .attr('transform', (_, i, a) => `translate(${boxX + boxW},${boxY + rowY(i, a.length)})`);
  exp.append('title').text((d) => d.tooltip);
  exp.append('line').attr('x1', 0).attr('x2', rightGutter - L.r * 2).attr('y1', 0).attr('y2', 0)
    .attr('stroke', C.ink).attr('stroke-width', 2);
  exp.append('circle').attr('cx', rightGutter - L.r).attr('cy', 0).attr('r', L.r)
    .attr('fill', C.paper).attr('stroke', C.ink).attr('stroke-width', 1.5);
  exp.append('text').attr('x', (rightGutter - L.r) / 2).attr('y', -7).attr('text-anchor', 'middle')
    .attr('fill', C.ink).attr('font-weight', (d) => (d.required ? 'bold' : null)).text((d) => d.label);

  // note under the box
  svg.append('text').attr('x', boxX).attr('y', boxY + boxH + 20).attr('font-style', 'italic')
    .attr('font-size', 11).attr('fill', C.muted)
    .text(`Source: component.yaml v${model.version}${model.functionalBlock ? ` · ${model.functionalBlock}` : ''} · bold API = required`);

  drawLegend(svg, L.margin, legendY, pageW - L.margin * 2, L.legendH);

  return new XMLSerializer().serializeToString(svg.node()) + '\n';
}

function drawLegend(svg, x, y, w, h) {
  const g = svg.append('g').attr('id', 'legend').attr('transform', `translate(${x},${y})`);
  g.append('rect').attr('width', w).attr('height', h).attr('rx', h / 2)
    .attr('fill', C.paper).attr('stroke', C.ink).attr('stroke-width', 1.5);
  g.append('text').attr('x', 40).attr('y', h / 2).attr('dy', '0.35em').attr('font-weight', 'bold').text('LEGEND');

  const slot = (w - 140) / 4, cy = h / 2;
  const item = (i, label, draw) => {
    const s = g.append('g').attr('transform', `translate(${140 + i * slot},${cy})`);
    draw(s);
    s.append('text').attr('x', 60).attr('dy', '0.35em').attr('fill', C.ink).text(label);
  };
  item(0, 'eTOM Business Activity', (s) =>
    s.append('rect').attr('x', 0).attr('y', -10).attr('width', 50).attr('height', 20).attr('fill', C.paper).attr('stroke', C.ink));
  item(1, 'SID Data Entity', (s) => {
    s.append('path').attr('fill', C.paper).attr('stroke', C.ink)
      .attr('d', 'M0,-8 A25,4 0 0 1 50,-8 V8 A25,4 0 0 1 0,8 Z');
    s.append('path').attr('fill', 'none').attr('stroke', C.ink).attr('d', 'M0,-8 A25,4 0 0 0 50,-8');
  });
  item(2, 'Dependent API', (s) => {
    s.append('path').attr('fill', 'none').attr('stroke', C.ink).attr('stroke-width', 2).attr('d', 'M10,-10 A10,10 0 0 1 10,10');
    s.append('line').attr('x1', 20).attr('x2', 50).attr('stroke', C.ink).attr('stroke-width', 2);
  });
  item(3, 'Exposed API', (s) => {
    s.append('line').attr('x1', 0).attr('x2', 30).attr('stroke', C.ink).attr('stroke-width', 2);
    s.append('circle').attr('cx', 40).attr('r', 10).attr('fill', C.paper).attr('stroke', C.ink).attr('stroke-width', 1.5);
  });
}
